version: "3.8"

services:
  web:
    build: .
    image: messagingservice:latest
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=messagesdb;Username=postgres;Password=password
    networks:
      - messagingnet

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messagesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - messagingnet

volumes:
  pgdata:

networks:
  messagingnet:
    driver: bridge
